### ISSUE TITLE
GenericModel<String> serialization doesn't seem to be working properly

### ISSUE THREAD

**Issue by axiopisty** [nicks101/flutter_tutorials#2]
First, thank you for your article and sharing this project. It's been really helpful.

I'm trying to work through your solution to understand how the serializers work. I ended up forking your repository, upgrading the project to the newest version of flutter (commit 1), adding a new test case that validates  `GenericModel.fromJson<MyModel>(model.toJson()), model)` (commit 2), and attempts to validate `GenericModel.fromJson<String>(model.toJson()), model)` (commit 3) but this last validation fails with the message:

> Deserializing to 'GenericModel<String>' failed due to: Deserializing to 'BuiltList<String>' failed due to: Deserializing to 'String' failed due to: type 'List<Object?>' is not a subtype of type 'String' in type cast

Would you mind having a look at the commits on my fork of your repository and helping me understand what the problem is? Why does it work with `MyModel` but not with `String`?

I'm going to submit a pull request to your repository that contains the changes that I've made. As a note, the project builds, compiles, and passes all tests if using my first 2 commits, but fails when using my 3rd commit due to the error message I'm reporting and asking for help with in this ticket.

**Comment by nicks101** [comment]
Glad it helped!
The problem was with the `toJson()` in `GenericModel`. It's fixed now with [commit](https://github.com/nicks101/flutter_tutorials/commit/24d18e31803a5e62d3aa499e66111893e29a2de7).
The tests should work. Thanks for bringing this to my attention.
Can you verify? Will merge the PR then.
As to why the `String` type was not working vs `MyModel`, not sure. Will have to look into it further.

**Comment by axiopisty** [comment]
Thank you for your quick response Nikki. I merged your changes into my PR and validated the results. Everything is working now so I think the PR is ready to be merged if you would like to update your repository.

If you're feeling up to it, I think it would be nice if you would either update your blog post to explain why these changes were needed, or just post a new blog entry about it.

I really appreciate that you are sharing your experiences on your blog. I'm sure that's a great help to you, and to others. I know it has been helpful to me.

Sincerely,
Elliot

PS: Feel free to reach out if you would like to discuss things more, or collaborate on any projects.

**Comment by nicks101** [comment]
The PR is merged! Thanks for adding those tests. 
I’ve been on a bit of a hiatus with my blog writing, but I’ll definitely update this project related blog (hopefully soon).

I’d love to collaborate on projects, open to ideas.
